version: "3.9"

networks:
  app:
    driver: bridge

services:
  library:
    build: ./src/library
    ports:
      - 3002:3000
    restart: always
    volumes: 
      - ./src/library:/app
    depends_on:
      - counter
      - mongo
    networks:
      - app

  counter:
    build: ./src/counter
    volumes: 
      - ./src/counter:/app
    ports:
      - 3003:3000
    networks:
      - app

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: library
    volumes:
      - ./mongodb:/data/db        
    ports:
      - 27017:27017 
    networks:
      - app